### ISSUE TITLE
Setup error: PHP error occured : msg=Cannot declare class DashletStats, because the name is already in use

### ISSUE THREAD

**Issue by Molkobain** [AHalfWildSheep/itop-dashlet-stats#4]
Hello there,

**Symptom**
During the setup, it crashes with the module as the `DashletStats` class is declared twice.
```
Setup error: PHP error occured : msg=Cannot declare class DashletStats, because the name is already in use, no=64, file=C:\wamp64\apps\itop\dev-support-3.2\extensions\ahws-dashlet-stats\src\Application\DashletStats.php, line=17
```

**Reproduction**
  * iTop 3.1
  * Your module
  * Run the setup

**Cause**
It seems like the autoloader is not up-to-date, but I might be mistaken.

**Comment by AHalfWildSheep** [comment]
Hello @Molkobain,
Thanks for the info I'll check it later today. I seem to recall resolving a similar issue locally when I updated from 3.0 to 3.1.
Regards.

**Comment by AHalfWildSheep** [comment]
Hello @Molkobain,
I fixed the crash yesterday, please let me know if you are okay with me closing this issue.
Regards.

**Comment by Molkobain** [comment]
Perfect, thanks!
